# This file was generated by GoReleaser. DO NOT EDIT.
class RcSdm < Formula
    desc ""
    homepage "https://github.com/thestillheron/homebrew-replay-city/rc-sdm"
    version "0.1"
  
    on_macos do
      url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-sdm.tar.gz"
      sha256 "65e0c64aaf42b45c283b9ea2d714935015fb12bd1e1535323096f39c7e6afefb"
  
      def install
        prefix.install Dir["output/*"]
      end
    end
  end