# This file was generated by GoReleaser. DO NOT EDIT.
class RcSdm < Formula
    desc ""
    homepage "https://github.com/thestillheron/homebrew-replay-city/rc-sdm"
    version "0.1"
  
    on_macos do
      url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-sdm.tar.gz"
      sha256 "8ac0ddcb419f953f47a33fbf7e8667a9992d5eb9c9fb664b1e35cc0f4352c4b0"
  
      def install
        bin.install "*"
      end
    end
  end