# This file was generated by GoReleaser. DO NOT EDIT.
class RcTools < Formula
    desc ""
    homepage "https://github.com/thestillheron/homebrew-replay-city/rc-tools"
    version "0.1"
  
    on_macos do
      on_arm do
        url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-tools.tar.gz"
        sha256 "0997214793d6c25953b99f80a8a897b90cb8586870b742f29bfa9bdbfa3de85d"
    
        def install
          bin.install Dir["arm64/*"]
        end
      end

      on_intel do
        url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-tools.tar.gz"
        sha256 "0997214793d6c25953b99f80a8a897b90cb8586870b742f29bfa9bdbfa3de85d"
    
        def install
          bin.install Dir["x64/*"]
        end
      end
    end
  end
