# This file was generated by GoReleaser. DO NOT EDIT.
class RcTools < Formula
    desc ""
    homepage "https://github.com/thestillheron/homebrew-replay-city/rc-tools"
    version "0.1"
  
    on_macos do
      on_arm do
        url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-tools.tar.gz"
        sha256 "2a4eaa66e9b06672a1e79428a21a4058e4a72337d8782d89a749fe4af0587c0c"
    
        def install
          bin.install Dir["arm64/*"]
        end
      end

      on_intel do
        url "https://replaycityapi-distributionbucket41178fc6-9ze5rgy0nrnn.s3.ap-southeast-2.amazonaws.com/rc-tools.tar.gz"
        sha256 "2a4eaa66e9b06672a1e79428a21a4058e4a72337d8782d89a749fe4af0587c0c"
    
        def install
          bin.install Dir["x64/*"]
        end
      end
    end
  end
