# This file was generated by GoReleaser. DO NOT EDIT.
class RcTools < Formula
    desc ""
    homepage "https://github.com/thestillheron/homebrew-replay-city/rc-tools"
    version "0.1"
  
    on_macos do
      on_arm do
        url "https://assets.replaycity.tech/0.0.1/mac/rc-tools.tar.gz"
        sha256 "904a69c361281d6f188b7b35717e9cd19822b4b3bc88369a52f1a150cfe3d2f1"
    
        def install
          bin.install Dir["arm64/*"]
        end
      end

      on_intel do
        url "https://assets.replaycity.tech/0.0.1/mac/rc-tools.tar.gz"
        sha256 "904a69c361281d6f188b7b35717e9cd19822b4b3bc88369a52f1a150cfe3d2f1"
    
        def install
          bin.install Dir["x64/*"]
        end
      end
    end
  end
